### ISSUE TITLE
Colosseum-ue-5.3 python api

### ISSUE THREAD

**Issue by V7KX** [CodexLabsLLC/Colosseum#103]
## Bug report 

- AirSim Version/#commit:
- UE/Unity version:5.3
- autopilot version:
- OS Version:win11

### What's the issue you encountered?

Colosseum-ue-5.3的python api：`client.takeoffAsync()`和`client.landAsync()`正常可用，
但是`client.moveToPositionAsync`和`client.moveToPositionAsync`等控制无人机的api不能用，无人机会直接跳过此代码，python不会报错。

### How can the issue be reproduced?

1.
2.

### Include full error message in text form
```requestApiControl was successful
Vehicle is already armed
API call was not received, entering hover mode for safety Vehicle is disarmed
releaseApiControl was successful
State: Disarmed
'DisableAllScreenMessages'进行抑制```


**What's better than filing an issue? Filing a pull request :).**

**Comment by xxEoD2242** [comment]
Current branch supports 5.4 only

**Comment by V7KX** [comment]
> Current branch supports 5.4 only

Oh thank you, I downloaded the version too early, now my problem has been solved!
