### ISSUE TITLE
build.cmd failed

### ISSUE THREAD

**Issue by June-Smith** [CodexLabsLLC/Colosseum#108]
## Bug report 
&lt;!-- If any section does not apply, replace its contents with "N/A". --&gt;
- AirSim Version/#commit:1.2 main branch
- UE/Unity version:5.2.1
- autopilot version:not use
- OS Version:windows10

### What's the issue you encountered?

I've checked my network, and it's not a network issue. I deleted the entire project, redownloaded it from your homepage, and tried again, but it still failed. I don't know why it's failing. I hope you can help me.
![微信图片_20240920161350](https://github.com/user-attachments/assets/c74991af-e18d-41f5-9534-db09b2392c54)

### Settings

Actually, I'm not sure what I did. During the VS2022 installation, I chose to install almost all components since I have ample storage. Afterwards, I downloaded your project and executed build.cmd, but it failed.

### How can the issue be reproduced?

Could the issue stem from the VS2022 installation? I have the latest VS2022 version installed, along with all components for both C++ desktop and game development. I also selected all optional components, including SDKs, the .NET Framework, and others.

### Include full error message in text form
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\__msvc_iter_core.hpp(493,40):
 warning C4996: 'stdext::checked_array_iterator<Char *>': warning STL4043: stdext::checked_array_iterator, stdext::unch
ecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std:
:span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or
_SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning. [C:\UEAir\Colosseum-main\external\rpclib\rpclib-2.3.
1\build\rpc.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\__msvc_iter_core.hpp(493,40):
 warning C4996:         with [C:\UEAir\Colosseum-main\external\rpclib\rpclib-2.3.1\build\rpc.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\__msvc_iter_core.hpp(493,40):
 warning C4996:         [ [C:\UEAir\Colosseum-main\external\rpclib\rpclib-2.3.1\build\rpc.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\__msvc_iter_core.hpp(493,40):
 warning C4996:             Char=wchar_t [C:\UEAir\Colosseum-main\external\rpclib\rpclib-2.3.1\build\rpc.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\__msvc_iter_core.hpp(493,40):
 warning C4996:         ] [C:\UEAir\Colosseum-main\external\rpclib\rpclib-2.3.1\build\rpc.vcxproj]
  (编译源文件“../lib/rpc/server.cc”)
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\iterator(1493,35):
      参见“stdext::checked_array_iterator”的声明
          新目录           1    C:\UEAir\Colosseum-main\external\rpclib\rpclib-2.3.1\build\Release\
100%        新文件                 2.6 m        rpc.lib

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         1         0         0         0         0
       文件:         1         1         0         0         0         0
       字节:    2.65 m    2.65 m         0         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00

       速度:           1391158000 字节/秒。
       速度:            79602.699 MB/分钟。
   结束时间: 2024年9月20日 16:02:55

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2024年9月20日 16:02:55
        源: C:\UEAir\Colosseum-main\external\rpclib\rpclib-2.3.1\build\RelWithDebInfo\
      目标: C:\UEAir\Colosseum-main\AirLib\deps\rpclib\lib\x64\RelWithDebInfo\

      文件: *.*

      选项: *.* /S /E /DCOPY:DA /COPY:DAT /PURGE /MIR /R:1000000 /W:30

------------------------------------------------------------------------------

          新目录           2    C:\UEAir\Colosseum-main\external\rpclib\rpclib-2.3.1\build\RelWithDebInfo\
100%        新文件                 6.0 m        rpc.lib
100%        新文件                 2.4 m        rpc.pdb

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         1         0         0         0         0
       文件:         2         2         0         0         0         0
       字节:    8.46 m    8.46 m         0         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00

       速度:           1478989666 字节/秒。
       速度:            84628.467 MB/分钟。
   结束时间: 2024年9月20日 16:02:55

*****************************************************************************************
Configure High Polycount SUV car model
*****************************************************************************************
Not downloading high-poly car asset. The default unreal vehicle will be used.

*****************************************************************************************
Setup Eigen dependency for AirLib
*****************************************************************************************
Submodule ExternalRepositories\Colosseum_Eigen not properly initialized. Try running 'git submodule update --init'
*****************************************************************************************
Build failed!
*****************************************************************************************
Build failed - see messages above.

**Comment by FloralHercules** [comment]
Hi, I meet the same problem? Could you tell me how to resolve it? Very Thanks, looking forward to your reply.
