### ISSUE TITLE
Fail to build by UE 5.0 on windows 10.

### ISSUE THREAD

**Issue by Leon-xc** [CodexLabsLLC/Colosseum#17]
Hi~ 
I try to build Colosseum by UE 5. but it failed. Have Colosseum fixed for UE5?

Thanks for answering.

version:  
UE 5.0.3 + VS2022  + .net framework 4.7.2

**Comment by xxEoD2242** [comment]
Hey @Leon-xc,

First, did you install .Net Development Kit 3.0.X? (It should be 3.0.4 or something close to that).

Did you run `clean_rebuild.bat` with the developer prompt?

You need to then go to the Blocks folder and open the Blocks.sln file and then build the project from there. There are other issues related to materials I am looking at fixing right now.

**Comment by Leon-xc** [comment]
Thank for your patient answering~
1. I success to build UE5-branch for UE5. But I cannot operate cars like what i did in UE4 (forward, back, turning around ). This branch 
 don't support keyboard control, right? So Does it mean to control it by  python API ？

it seems that the car cannot fall on the ground (like the pic following)
![image](https://user-images.githubusercontent.com/39732488/202716062-1f230dab-58a8-474d-acfc-a275ed2a76a4.png)


2. Also, I cannot find .Net framework 3.0 develop kit  on VS2022 install.(As the pictures shows, the closest version is .Net develop kit 3.5)  It seems that 3.0 version is too old that Microsoft stop supporting it. To my best effort, I can only find .net 3.0 runtime sdk  on the internet.
![image](https://user-images.githubusercontent.com/39732488/202712946-69eb9070-57bc-41be-8167-484dce5c697f.png)

Thank you so much for your patience again. Feel sorry if my question is really basic.

**Comment by xxEoD2242** [comment]
@Leon-xc Interesting. If you don't have the errors with 3.0.X then you should be good. I had that error when building but it may have been my VS was out of date. I had to do a full reinstall of VS22 to get everything working.

The car is very odd and I have only really tried the UAV to test out APIs and such.

I will explore the car and let you know. This is still highly experimental at the moment.

**Comment by Leon-xc** [comment]
Thanks for your effort~
The only way to run it is to operate by python api, right ?

**Comment by xxEoD2242** [comment]
To be honest, I haven't tried out the APIs on the Car. APIs on the UAV worked great though.

If you try, let me know the result

**Comment by Leon-xc** [comment]
OK~

**Comment by xxEoD2242** [comment]
@Leon-xc 

After digging around, it appears that the animation that runs the actual vehicle is broken, since it was based on PhysX and UE5 has moved to Chaos physics only. I am in the process of fixing that but it also appears that there are some issues related to how that animation plays with the old vehicle.

Most likely, we will need to just rebuild the vehicle in UE5 to be the Chaos vehicle.

**Comment by Leon-xc** [comment]
@xxEoD2242 Wow, I get it. But i wonder how it can pass compiling when the PhysX doesn't work ? Is the code of PhysX deleted to pass compiling?

**Comment by xxEoD2242** [comment]
Colosseum itself will compile since those files are `.uasset` files that don't get compiled. It only complains when you load them into the vehicle. I'll ask the person who did the work if they forgot to add the asset files in the plugin

**Comment by xxEoD2242** [comment]
@Leon-xc I updated the urls in the build.cmd and setup.sh files so the new assets are hosted for UE5

**Comment by xxEoD2242** [comment]
If you do a pull on that branch, delete the old SUV folder in the plugins and then run build.cmd again, it will download the right assets.

**Comment by Leon-xc** [comment]
@xxEoD2242 wow，I get it. Thank u for helping~

**Comment by xxEoD2242** [comment]
@Leon-xc Let me know if you need anything else and feel free to reach out to me on Slack/email.
