### ISSUE TITLE
Slack link

### ISSUE THREAD

**Issue by andrewjong** [CodexLabsLLC/Colosseum#19]
Hi! I'd like to get involved on the Colosseum Slack but it appears the Slack invite link on the Readme is expired.

**Comment by xxEoD2242** [comment]
Hey Andrew,

Thanks for letting me know.

Here is a new link and I'll update the README

Join me on Slack -- it’s a faster, simpler way to work. Sign up here, from any device: [Link](https://join.slack.com/t/colosseum-sim/shared_invite/zt-1ljqpik8x-UtBvY2yraQb9p98udzjoQw)

**Comment by YeiSimon** [comment]
I would like to get involved in the Colosseum Slack but the links on the Readme seems expired.

**Comment by xxEoD2242** [comment]
@YeiSimon I updated the README but here is the link as well: [Colosseum Slack](https://join.slack.com/t/colosseum-sim/shared_invite/zt-1qwrbtz1d-WCGpYhJ8sDrYTv8fk50pFg)

**Comment by CalebSpencerTorch** [comment]
@xxEoD2242 I want to get in on whatever community discussions there are. That Slack link is inactive. Old Discord links I've found are also invalid. Is there a way to make a permanent link that won't need replacing so often?

**Comment by xxEoD2242** [comment]
Click the button on the main page. It’s a forever link to Discord

**Comment by xxEoD2242** [comment]
> @xxEoD2242 I want to get in on whatever community discussions there are. That Slack link is inactive. Old Discord links I've found are also invalid. Is there a way to make a permanent link that won't need replacing so often?

Click the Discord button on the main page. It's a forever link

**Comment by xxEoD2242** [comment]
![Screen Shot 2023-08-08 at 10 57 48 AM](https://github.com/CodexLabsLLC/Colosseum/assets/32143517/83f0d3ee-634e-481b-8ffa-bba8bfb523fb)

I was referring to the badge at the top of the README. I honestly forgot that link was even there

Here is the forever link: [Discord Forever Link](https://discord.gg/y9ZJKKKn8J)
