### ISSUE TITLE
Ubuntu CI fails unzip car_assets

### ISSUE THREAD

**Issue by alonfaraj** [CodexLabsLLC/Colosseum#32]
## Bug report 
Ubuntu CI is now failing because an issue with car_assets zip file.
To fix it we should make a zip file from Ubuntu and re-upload.
I tested it locally and it looks fine.
@xxEoD2242 This can be done by only by you.

### Include full error message in text form
`warning:  car_assets.zip appears to use backslashes as path separators`
https://github.com/CodexLabsLLC/Colosseum/actions/runs/4124215191/jobs/7123199180#step:3:1275

**Comment by xxEoD2242** [comment]
@alonfaraj On it!

**Comment by xxEoD2242** [comment]
Fixed!
