### ISSUE TITLE
Segmentation images don't show any static mesh with Nanite enabled

### ISSUE THREAD

**Issue by gstcyr** [CodexLabsLLC/Colosseum#47]
## Bug report 

- AirSim Version/#commit: #main
- UE/Unity version: UE 5.1.1
- autopilot version: n/a
- OS Version: Windows 10

### What's the issue you encountered?

If Nanite is enabled on a static mesh, it will no longer appear in Segmentation View or in any Segmentation Image Requests

### How can the issue be reproduced?

1. Enable Nanite on a Static Mesh in your scene
2. Hit play, and then turn on Segmentation View (2)

### Include full error message in text form

**What's better than filing an issue? Filing a pull request :).**

**Comment by gstcyr** [comment]
https://forums.unrealengine.com/t/render-custom-depth-on-nanite-enabled-not-working/505390/18

This isn't an issue with Colosseum, it's an issue with Nanite Meshes not showing in the Stencil buffer. Going to close here.

**Comment by xxEoD2242** [comment]
Hey @gstcyr,

Thanks for adding that note. This has been solved in UE5.2, which is the currently supported version for the main branch. Let me know if you have any issues.
