### ISSUE TITLE
Slack invite no longer active.

### ISSUE THREAD

**Issue by robodrome** [CodexLabsLLC/Colosseum#51]
### What's the issue you encountered?
Slack invite mentioned in README.md, Join the Community section, is not working: "This link is no longer active"

**Comment by xxEoD2242** [comment]
Hey @robodrome I have updated the link and added it [here](https://join.slack.com/t/colosseum-sim/shared_invite/zt-1vqt3ydx2-D7uLLZb5Om1_wy7wUermXA)

**Comment by jesse-wei** [comment]
> Hey @robodrome I have updated the link and added it [here](https://join.slack.com/t/colosseum-sim/shared_invite/zt-1vqt3ydx2-D7uLLZb5Om1_wy7wUermXA)

This is also no longer active.

**Comment by MehmetCagriK** [comment]
> Hey @robodrome I have updated the link and added it [here](https://join.slack.com/t/colosseum-sim/shared_invite/zt-1vqt3ydx2-D7uLLZb5Om1_wy7wUermXA)

Hello, can we have an updated link?

**Comment by xxEoD2242** [comment]
@MehmetCagriK I fixed the Discord Link on the README. Let me know if you have issues.

**Comment by xxEoD2242** [comment]
Done
