### ISSUE TITLE
cant use built model 

### ISSUE THREAD

**Issue by reza-shahriari** [CodexLabsLLC/Colosseum#62]
### can you please explain step-by-step how to use it? 
I have cloned your repo and then built it with vs 2022 now I cant use blocks nor plugin!.
both of them showing this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1900	Il mismatch between 'P1' version '20210224' and 'P2' version '20210202'	MyProject7	C:\Users\iust\Documents\Unreal Projects\MyProject7\Intermediate\ProjectFiles\EXEC	
what should i do ?

**Comment by ides2327** [comment]
Strangely having this exact issue right now, using unreal 5.2.1. Tried VS2022 and 2019 with no luck...

**Comment by xxEoD2242** [comment]
@reza-shahriari Do you have multiple versions of Visual Studio installed?

You also need to do a clean on Blocks (delete the Intermedate and Binaries folder), then build again.

This is because when you switch UE versions, you have to switch VS versions, which cause conflicts with the build process. This is an Unreal Engine issue that I still have not found a way to automate.

**Comment by reza-shahriari** [comment]
@xxEoD2242 Thanks for answering fast!
I had vs 2015 installed and I deleted it but steal seeing the error :(
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1900	Il mismatch between 'P1' version '20210224' and 'P2' version '20210202'	Blocks	D:\AirSim-Unreal\New folder\Colosseum\Unreal\Environments\Blocks\Intermediate\ProjectFiles\EXEC	1	
would you help me please?

**Comment by xxEoD2242** [comment]
You need to install VS 2022 and then remove those folders I mentioned.

**Comment by xxEoD2242** [comment]
> i have airsim and unreal 4.27 installed. is it any problem with it?

That shouldn't be an issue as long as you are in Colosseum

**Comment by reza-shahriari** [comment]
Thanks again 
i have VS2022. removed the folder you said by clean.sh . then i used clean.sh in the main folder and build it again but steal not working for me:(

**Comment by xxEoD2242** [comment]
> Thanks again 
> 
> i have VS2022. removed the folder you said by clean.sh . then i used clean.sh in the main folder and build it again but steal not working for me:(
> 
> 

Did you remove all other versions of VS?

**Comment by reza-shahriari** [comment]
Yes
I uninstalled all the other versions

**Comment by reza-shahriari** [comment]
can you help me in real time mate? i mean monitor sharing or remote ... it will be nice if you do

**Comment by xxEoD2242** [comment]
Unfortunately, we are super busy with our new product launch this week.

If I have time next week, we could possibly meet. In the meantime, I would recommend getting on Discord and asking your question there.

**Comment by reza-shahriari** [comment]
would you please share the link

**Comment by xxEoD2242** [comment]
> would you please share the link
> 
> 

It's on the readme. Click on the Badge that says Colosseum Robotics Simulator

**Comment by reza-shahriari** [comment]
Thanks a lot 🙏🙏

**Comment by ides2327** [comment]
Just fixed this problem for myself. I had VS Build Tools 2019 while my VS Community was 2022. Maybe try checking your version of build tools.

**Comment by reza-shahriari** [comment]
@ides2327  i'll check it thanks for help

**Comment by reza-shahriari** [comment]
@ides2327  i'll check it thanks for help

**Comment by batuhanuzaldimvc** [comment]
Solved my issue.

I thought I needed to download the exact Windows SDK version mentioned in [the docs](https://github.com/microsoft/AirSim/blob/main/docs/build_windows.md#build-airsim), turns out I need to get the latest one listed in the VSC installation list.

**Comment by reza-shahriari** [comment]
> Solved my issue.
> 
> I thought I needed to download the exact Windows SDK version mentioned in [the docs](https://github.com/microsoft/AirSim/blob/main/docs/build_windows.md#build-airsim), turns out I need to get the latest one listed in the VSC installation list.

i have uninstalled all the other versions of SDKs but i am steal seeing the error

**Comment by batuhanuzaldimvc** [comment]
> > Solved my issue.
> > I thought I needed to download the exact Windows SDK version mentioned in [the docs](https://github.com/microsoft/AirSim/blob/main/docs/build_windows.md#build-airsim), turns out I need to get the latest one listed in the VSC installation list.
> 
> i have uninstalled all the other versions of SDKs but i am steal seeing the error

Make sure to uninstall all other versions of VS, even the versions of 2022 (17.7, 17.6 etc.). Best way to do it is completely uninstalling the all VS related programs including the installer, as mentioned above by others.

Then do a clean installation after restarting your system. During the installation, just to be safe, select all Microsoft SDK versions, select the latest .NET Framework.

Might also help;
Start the VS with admin rights. To do that with the sln files, you need to right click the "devenv.exe" to open the troubleshoot compatibility screen then select "this program requires additional permissions".

**Comment by reza-shahriari** [comment]
> 

ill try it ASAP
thanks for the comment

**Comment by reza-shahriari** [comment]
> Make sure to uninstall all other versions of VS, even the versions of 2022 (17.7, 17.6 etc.). Best way to do it is completely uninstalling the all VS related programs including the installer, as mentioned above by others.
> 
> Then do a clean installation after restarting your system. During the installation, just to be safe, select all Microsoft SDK versions, select the latest .NET Framework.
> 
> Might also help; Start the VS with admin rights. To do that with the sln files, you need to right click the "devenv.exe" to open the troubleshoot compatibility screen then select "this program requires additional permissions".

THANKSSSSSSS
i have airsim in ue5 now 
I had to reinstall it as you said
thanks a lot
