### ISSUE TITLE
Could not find any instance of visual studio error while trying to run build.cmd

### ISSUE THREAD

**Issue by nl22-nmsu** [CodexLabsLLC/Colosseum#68]
Hello,

I was following the Airsim tutorial and made it as far as running "build.cmd". I get an error "Could not find any instance of visual studio".

Currently, I'm working on a Windows 11 machine with Unreal Engine 5, Visual Studio 2022, and Cmake version 3.27.6.

I've already tried running the developer command prompt as administrator with no luck. I also tried the Airsim repo and a recommended fork of that repo that I found on the Airsim "issues" page, but no luck there. 

Anyone know what the fix is?

**Comment by nl22-nmsu** [comment]
For anyone else who may have this issue, I was able to solve this by opening VS 2022 and going to "Tools->Get Tools and Features ". Make sure to select "Desktop development with C++".  After downloading that it builds.

**Comment by pppppsb** [comment]
@nl22-nmsu 
Why can't I compile after opening the BlocksV2.sln file with VS2022? I downloaded the desktop development of C++.
![Image](https://github.com/user-attachments/assets/fbf7294f-b2de-41a9-9db7-97d8eeb44282)
