### ISSUE TITLE
PackagingResults : Error: cannot initialize a variable of type 'const UClass *' with an lvalue of type  'FFieldClass *'

### ISSUE THREAD

**Issue by jiaxiaofeng666** [CodexLabsLLC/Colosseum#75]
## Bug report 

- AirSim Version/#commit: latest Release V2.1.0
- UE/Unity version: Unreal 5.2.1
- autopilot version:
- OS Version: Ubuntu 20.04

### What's the issue you encountered?

I created a new C++ project using the UE5.2.1 version on ubuntu20.04, and then compiled the source code of airsim v2.1.0(https://github.com/CodexLabsLLC/Colosseum/releases/tag/v2.1.0), and also put the airsim plug-in in the Plugins directory of the new project. After that, the project compiled and ran successfully, and I was also editing I saw the drone model when running the server, but when I packaged the project into an executable file under the Linux platform, I got the following error:

![20240118-124632](https://github.com/CodexLabsLLC/Colosseum/assets/53074933/d1d0b3f0-bda9-43af-841e-826094ef4243)

This error also occurs on Windows. Is there a bug in the packaging process of this version of airsim?

I used UE5.0.3 and another version of airsim (https://github.com/czero69/AirSim/tree/ue5-cv) on ubuntu20.04. It successfully ran and packaged without any errors. Please tell me why the above UE5.2.1 Will the above error occur when using arsim v2.1.0 for packaging?

### How can the issue be reproduced?

1.Create a new C++ project using UE5.2.1 under Ubuntu20.04
2.Download the source code of airsim V2.1.0 to the root directory, and then execute the following command to compile the airsim plugin
```
cd AirSim
./setup.sh
./build.sh
```
Then put the ~/Unreal/Plugins/AirSim plug-in under the Plugins directory in the new project. The new project needs to create a new Plugins directory
3.then compile and run, and package the Linux platform package after successful operation.

### Include full error message in text form

If you have any other questions, please contact me, my email is 1600927475@qq.com

**What's better than filing an issue? Filing a pull request :).**

**Comment by IaroslavS** [comment]
> ## Bug report
> 
>     * AirSim Version/#commit: latest Release V2.1.0
> 
>     * UE/Unity version: Unreal 5.2.1
> 
>     * autopilot version:
> 
>     * OS Version: Ubuntu 20.04
> 
> 
> ### What's the issue you encountered?
> 
> I created a new C++ project using the UE5.2.1 version on ubuntu20.04, and then compiled the source code of airsim v2.1.0(https://github.com/CodexLabsLLC/Colosseum/releases/tag/v2.1.0), and also put the airsim plug-in in the Plugins directory of the new project. After that, the project compiled and ran successfully, and I was also editing I saw the drone model when running the server, but when I packaged the project into an executable file under the Linux platform, I got the following error:
> 
> ![20240118-124632](https://private-user-images.githubusercontent.com/53074933/297620101-d1d0b3f0-bda9-43af-841e-826094ef4243.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODY5NjksIm5iZiI6MTcxMzg4NjY2OSwicGF0aCI6Ii81MzA3NDkzMy8yOTc2MjAxMDEtZDFkMGIzZjAtYmRhOS00M2FmLTg0MWUtODI2MDk0ZWY0MjQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE1Mzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZTRhMmNlMTJkNjZjZmI3NTlkYzJjZTkwZmU3ZTM0Yzc4ZjU1NTQ1NDgxZTIwM2RiMGVmM2E0OTk0YmE2MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rwZ7BtjMblHTodG5sYoAeZvgRXkjj7IkXxUEXr1y_c)
> 
> This error also occurs on Windows. Is there a bug in the packaging process of this version of airsim?
> 
> I used UE5.0.3 and another version of airsim (https://github.com/czero69/AirSim/tree/ue5-cv) on ubuntu20.04. It successfully ran and packaged without any errors. Please tell me why the above UE5.2.1 Will the above error occur when using arsim v2.1.0 for packaging?
> ### Settings
> ### How can the issue be reproduced?
> 
> 1.Create a new C++ project using UE5.2.1 under Ubuntu20.04 2.Download the source code of airsim V2.1.0 to the root directory, and then execute the following command to compile the airsim plugin
> 
> ```
> cd AirSim
> ./setup.sh
> ./build.sh
> ```
> 
> Then put the ~/Unreal/Plugins/AirSim plug-in under the Plugins directory in the new project. The new project needs to create a new Plugins directory 3.then compile and run, and package the Linux platform package after successful operation.
> ### Include full error message in text form
> 
> If you have any other questions, please contact me, my email is [1600927475@qq.com](mailto:1600927475@qq.com)
> 
> **What's better than filing an issue? Filing a pull request :).**

Find 'Plugins/AirSim/Source/SimMode/SimModeBase.cpp' line 232 and replace Cast with CastFieldChecked. It's a software crutch (because you remove compatibility with some other versions of Unreal), but it works.

**Comment by xxEoD2242** [comment]
Please reopen if this is an issue in UE 5.4
