### ISSUE TITLE
ImageRequest with pixels_as_float = True very slow

### ISSUE THREAD

**Issue by samynjonas** [CodexLabsLLC/Colosseum#78]
## Bug report
- AirSim Version/#commit: Latest with small tweaks
- UE/Unity version: UE 5.2
- OS Version: win 11

### What's the issue you encountered?
As mentioned in the title turning on pixels_as_floats for an image request is very slow through the API, for the project I am working on I need depth images with a resolution of 1920x1080, before this I used the recording feature which was quick enough but I needed more control and moved to the python API. For the segmentation and scene images it is still fast enough but when I request a depth image, where I need to enable pixels as float to get acurate results, it is very slow, slow as I have never seen it complete a request with 1920x1080. It is fine for 255x144 and 1280x720 while also very slow also generated something at least but I would really like 1920x1080 images.

I think the problem lies with the connection between UE and python and it just not being fast enough to send this amount of data?

### Settings
Mostly default just camera settings set to 1920x1080

**What's better than filing an issue? Filing a pull request :).**

**Comment by xxEoD2242** [comment]
1080p images are large and you need a good graphics card to get good performance. Recommend using ROS but images will still be slow
