### ISSUE TITLE
 PNG images of type 0 recorded are transparent!

### ISSUE THREAD

**Issue by blanklog** [CodexLabsLLC/Colosseum#81]
## Bug report 

- AirSim Version/#commit: latest colloseum
- UE/Unity version:  5.2
- autopilot version:
- OS Version:  win10

### What's the issue you encountered?

UE5.2 and latest colloseum in Win10.  recording RGBA images are transparent，which alpha channel is all zero.

### How can the issue be reproduced?

1.
2.

### Include full error message in text form

**What's better than filing an issue? Filing a pull request :).**

**Comment by xxEoD2242** [comment]
Need more info here. What are you using, how are you getting images, etc. Please post code and repoduce when you reopen.
