### ISSUE TITLE
WHAT!!!??UPDATE UE5.3 BUT HAS MILLONS ERROR!!!?? ;(

### ISSUE THREAD

**Issue by JamesLJ2001** [CodexLabsLLC/Colosseum#83]
AirSim Version/#commit: this guys' https://github.com/joelreymont/AirSim.git 
UE/Unity version: Unreal 5.3.2
autopilot version:
OS Version: Windows 11
What's the issue you encountered?
I created a new C++ project using the UE5.3.2 version on Windows 11, and then fork code(https://github.com/joelreymont/AirSim.git) and run build.cmd from Developer Command Prompt for VS 2022, and also put the airsim plug-in in the Plugins directory of the new project. After that, the project compiled and ran unsuccessfully, I got the following error:
![image](https://github.com/CodexLabsLLC/Colosseum/assets/113606900/dda737f8-f069-4243-922b-7b7c0e320419)
![image](https://github.com/CodexLabsLLC/Colosseum/assets/113606900/c7056168-982e-48fc-99d3-e9f0e1836765)

and another guys‘  https://github.com/OpenSourceVideoGames/AirSim.git
![image](https://github.com/CodexLabsLLC/Colosseum/assets/113606900/389774ff-41b8-4d13-a97f-11836545c9c8)
![image](https://github.com/CodexLabsLLC/Colosseum/assets/113606900/3bd91ccd-e9b9-42ca-aa69-17e3ed573a68)

Is there a bug in the packaging process of this version of airsim?

Settings
How can the issue be reproduced?
1.Create a new C++ project using UE5.3.2 under Windows 11
2.Download the source code to the root directory, and then execute the following command to compile the airsim plugin
cd AirSim
build.cmd
Then put the ~/Unreal/Plugins plug-in under the Plugins directory in the new project. The new project needs to create a new Plugins directory
3.then compile and run.

Include full error message in text form
If you have any other questions, please contact me, my email is [1040987986@qq.com]

What's better than filing an issue? Filing a pull request :).

**Comment by Ravgni** [comment]
In file AirSim\Source\AirSim.Build.cs find line:

**Comment by mdsnyng** [comment]
I have the same issue. Right out of the box using 5.3 branch. Just trying to open the Unreal Blocks project that is included. The above change didn't help for me.

**Comment by xxEoD2242** [comment]
Main branch supports 5.4 only
