### ISSUE TITLE
Low FPS capturing while not using resources

### ISSUE THREAD

**Issue by reza-shahriari** [CodexLabsLLC/Colosseum#95]
- AirSim Version/#commit: [Colosseum](https://github.com/CodexLabsLLC/Colosseum)
- UE/Unity version: UE 5.27
- autopilot version: - 
- OS Version: windows 10

### Settings

[setting Gist](https://gist.github.com/reza-shahriari/065a2c8d89c602b89b3d8f61b2e7e1b6) 
### How can the issue be reproduced?

Hi
i am using Airsim to simulate drones(actually tow drones in an env)
everything works well but the problem is when i capture images from the camera.  i have a simple environment and a strong computer but arisim capturing about 5 images per second while i need at least 30!
not many resources are in use while running the project and capturing data:
![2024-07-20_17-12-51](https://github.com/user-attachments/assets/336e15fe-ecae-4aec-8f9d-6cc31d0d1489)

i dont know how i can improve the performance of the airsim! i used NoDisplay, changed SubWindows, and turned them off I also tested Python API but all are slow. i know i can add some sleep to my code then i can get the fps i wanted but for capturing a 10min video i should spend 60min then!

i have tested some other way to capture images from unreal. i mean just screenshotting or using a custom camera and rendering its view. both worked real time for me! and both were using more resources. i was trying to change this [code](https://github.com/microsoft/AirSim/blob/main/Unreal/Plugins/AirSim/Source/UnrealImageCapture.cpp#L32) to a faster way or at least make it just screenshotting to see if it works but did not work at all:(

do you have this problem too? Has anyone solved it?
thank,

**Comment by UnrealOrReal-Jack** [comment]
What a nice work you are doing. i have the same problem here!
would you try [this ](https://www.youtube.com/watch?v=YOidIl2kTD0)and tell me if it works?
it seems you can use opencv to render images and its working realtime in the video.
i am not experimented enough to do it but it would be nice if you do and tell me if its working :)
hope that helps
-**Jack**

**Comment by xxEoD2242** [comment]
I would recommend reducing your image size. 1080p is a lot for that system to render and what your seeing is the total lag of render + passing that through a network and reading it. This is a consequence of how AirSim (which is still the same code, haven't tried a new method yet) does image capturing through the view port. I would also recommend only doing 1 image stream at a time and repeating the process.

Another option is to build in a shared memory interface to do the image transfer, but that would be an enormous amount of work.

**Comment by reza-shahriari** [comment]
> would you try [this ](https://www.youtube.com/watch?v=YOidIl2kTD0)and tell me if it works?
I will try it and tell you asap
@xxEoD2242 Thanks for your fast answer.
Yeah having 1 viewport and NoDisplay may help but unfortunately, I need even more FPS.
As I have to do this project and I really need Big images (even bigger than 1080) would you tell me a little about the shared memory implementation? or if you have any other suggestions.
thanks again

**Comment by reza-shahriari** [comment]
I'm not sure if it's a fair comparison or not, but I've used the code below to capture images from a custom camera and save them in real time. The problem was that the lighting in the saved images wasn't as it should be.
```void AMyActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
    UGameViewportClient* GameViewport = GEngine->GameViewport;

    if (GameViewport)
    {
        FViewport* Viewport = GameViewport->Viewport;
        TArray<FColor> Bitmap;
        if (Viewport->ReadPixels(Bitmap))
        {
            int32 Width = Viewport->GetSizeXY().X;
            int32 Height = Viewport->GetSizeXY().Y;

            // Convert to OpenCV format
            cv::Mat Image(Height, Width, CV_8UC4, Bitmap.GetData());
            cv::Mat ImageBGR;
            cv::cvtColor(Image, ImageBGR, cv::COLOR_RGBA2BGR);

            // Save the image
            i++;

            std::string filePath = "C:/Users/AI-Control Lab/Pictures/Saved Pictures/OpenCVTestImage" + std::to_string(i) + ".png";
            cv::imwrite(filePath, ImageBGR);
            UE_LOG(LogTemp, Warning, TEXT("Screenshot saved as screenshot.png"));
        }
        else {
            UE_LOG(LogTemp, Warning, TEXT("NO screenSHOT at all :(("));
        }
    }
}```
![OpenCVTestImage1](https://github.com/user-attachments/assets/257b9563-f48b-4efe-80bb-517aa751b860)

**Comment by xxEoD2242** [comment]
Are you using Lumen for lighting?

**Comment by xxEoD2242** [comment]
> > would you try [this ](https://www.youtube.com/watch?v=YOidIl2kTD0)and tell me if it works?
> 
> I will try it and tell you ASAP
> 
> @xxEoD2242 Thanks for your fast answer. Yeah having 1 viewport and NoDisplay may help but unfortunately, I need even more FPS. As I have to do this project and I really need Big images (even bigger than 1080) would you tell me a little about the shared memory implementation? or if you have any other suggestions. do you know any other simulator that works with Unreal or Unity or any other engine that we can get realistic images and connect them to Arducopter? thanks again

You'd need to build a shared memory interface that you could copy data from another process. It's very non-trivial but i'm sure ChatGPT could provide you with an example of how to do it. That's the fastest way to move images. In terms of rate though, you'd probably see something on the order of 20 - 30 FPS just thinking through how this is done with the ViewPort RHIBuffer unlock.

I'd be interested to see a profile of how long it takes to get those images from the ViewPort. Also, that ViewPort is just what the character sees and isn't from a specific camera, right?

**Comment by xxEoD2242** [comment]
In terms of other simulators, I don't know of any that support ArduCopter and are Unity/UE. Try our Discord to see if anyone else has found anything

**Comment by reza-shahriari** [comment]
> Are you using Lumen for lighting?

Yes, the lighting method was Lumen but I have tested all combinations of lighting/reflection methods and none of them made sense
![2024-07-21_09-13-56](https://github.com/user-attachments/assets/94084b10-acfa-4f85-939b-be8f3c78e1ca)


> You'd need to build a shared memory interface that you could copy data from another process.

Ok, ill check it.



> Also, that ViewPort is just what the character sees and isn't from a specific camera, right?

yeah you are right. i thought its about cameras



> In terms of other simulators, I don't know of any that support ArduCopter and are Unity/UE. Try our Discord to see if anyone else has found anything

Thanks, ill ask it there.

**Comment by reza-shahriari** [comment]
ROS works nicely! I can capture at about 30 fps while having 25 drones on the screen.
 Thank you for your time and kindness :)

**Comment by hndxjxxy** [comment]
@reza-shahriari Hello, could you please explain in detail how the problem was ultimately resolved?
I also collect images at high resolution and use Rosbag for recording. I want a frequency of 15Hz, but I can only reach a maximum of 8Hz, and when I use the "rostopic hz" command to check, the frequency gradually increases. According to your last suggestion, is the increase in frame rate related to settings? Or have you built a shared memory interface?If you could share the solution, I would greatly appreciate it.

**Comment by reza-shahriari** [comment]
@hndxjxxy Hi,
actually i have not find any good answer to the question(yet)
even when just capturing the sky i get at most 20 fps now! i am in believe i have captured 40 hz in more complicated scene!
i have worked more with the client.getimage so ill share my experinces for this method dont sure about the ros. as i saw the ros package was calling the same function but instead of reading to the python was doing the reading in ROS and i dont think it should make ANY differents in the end
i just have tried different image capturing size (10* 10 to 4096*4096) the speed was almost the same! its all about the time being used for safty checks and no matter how the image capturing get time, it took about 0.05 seconds on my PC to make sure its safe to return the image and so i can't capture more than 20 hz even if i just capture 10*10!
as i found it about using different thread for image capturing but could not solve the problem to have a faster capturing way.

i also have tried the [ISSACSIM](https://github.com/isaac-sim/IsaacSim) + [PegasusSimulator](https://github.com/PegasusSimulator/PegasusSimulator) and its much better for timing both for the sensors and camera capture but in the end Airsim is realy better simulator for Dynamics.

i have a plan to add a better drone simulator to the isaacsim later but for now
if you just want to capture images for and the dynamics no matter i suggest to use isaacsim instead of unreal
but if not i suggest you to see the `RenderRequest.cpp` file and try to figure out if you can make the capturing faster

**Comment by jonyMarino** [comment]
@reza-shahriari If you’re interested in a drone simulator for Isaac Sim, you could consider extending [Project AirSim](https://github.com/iamaisim/ProjectAirSim/) to NVIDIA Omniverse. I’d be happy to help with that.

**Comment by reza-shahriari** [comment]
Hi @jonyMarino 
Thanks for the suggestion! I appreciate it.
I'm curious though – what does Project AirSim actually do in this context?
I was thinking about using Isaac Sim's built-in physics engine and just configuring my drone directly in there, letting Isaac Sim handle the physics predictions. I'm not sure if that's a good approach or not.
From what I've seen with AirSim, you could have something as unrealistic as a flying building using an F450 configuration! I'm looking for something more like what we have in Gazebo simulations – where you create your drone model and the simulator accurately simulates it based on your specific drone's actual configuration and physics(did not used it my self as i wanted a real scene rendering in the end)
Would the Isaac Sim approach work for that, or would extending AirSim be better?

**Comment by jonyMarino** [comment]
@reza-shahriari 
It really depends on what you’re trying to achieve.

What you can leverage from Project AirSim is the set of modular simulation libraries (simlibs) that are independent of the rendering engine. These allow you to plug in various physics and flight‑stack backends, for example JSBSim, Simulink, FastPhysics, SimpleFlight, PX4, ArduPilot, etc. without being tightly coupled to a specific graphics stack.

This modularity means you could integrate those simulation cores into Omniverse or Isaac Sim instead of Unreal Engine to take advantage of those platforms’ rendering capabilities, robotics toolchains, and performance optimizations, while still using the same underlying simulation logic from Project AirSim.

Ultimately, which approach is “better” depends on what you want in terms of performance, extensibility, and ecosystem.

**Comment by reza-shahriari** [comment]
@jonyMarino 
Thanks for clarifying
Gonna try the project airsim and try adding it to isaacsim later
Will ask you more questions if I had any problem 🙏

**Comment by hndxjxxy** [comment]
> as i found it about using different thread for image capturing but could not solve the problem to have a faster capturing way.

@reza-shahriari Thank you for your reply and sharing！！！
I tried your method, asynchronously obtaining left and right target images in the image processing thread, which successfully achieved the frequency I wanted.（My image size is 1280 * 1280）. This does not change the speed of capture function, but it can prevent blocking and standardize image timestamps (previously obtained images will be swapped between left and right eyes)

**Comment by reza-shahriari** [comment]
@hndxjxxy No problem
glad I helped you
I'll share my results if i find any way to capture images faster

**Comment by reza-shahriari** [comment]
@jonyMarino can we talk some where else like discord about the project airsim in Isaacsim?
my username is : reza_shahriari

**Comment by jonyMarino** [comment]
@reza-shahriari I've sent you an invite

**Comment by goodisok** [comment]
Hello, have you already resolved this issue? I'm encountering the same problem. I need 1920×1080 resolution images and require a higher frame rate. Do you have a suitable solution?

**Comment by reza-shahriari** [comment]
Hello @goodisok 
If you just want the video in high frame rate you can fly, save trajectory with required frame rate (say 30) into a text file then move the drone step by step and capture an image each step
